package api

import (
	"context"
	"fmt"
	"graph-interview/internal/api/middlewares"
	"graph-interview/internal/cfg"
	"graph-interview/pkg/logger"
	"os/signal"
	"syscall"

	// _ "gateway/swagger" // docs is generated by Swag CLI, you have to import it.

	_ "net/http/pprof"

	"github.com/gin-contrib/graceful"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

func genSwagHandler(baseURL string) gin.HandlerFunc {
	var conf func(*ginSwagger.Config)
	switch cfg.Cfg.Environment {
	case cfg.Local:
		conf = ginSwagger.URL(fmt.Sprintf("http://localhost:%d/swagger/doc.json", cfg.Cfg.Server.Port))
	default:
		conf = ginSwagger.URL(fmt.Sprintf("https://%s/swagger/doc.json", baseURL))
	}
	return ginSwagger.WrapHandler(
		swaggerFiles.Handler,
		conf,
		ginSwagger.PersistAuthorization(true),
	)
}

func ServeREST(ctx context.Context) error {

	ctx, stop := signal.NotifyContext(ctx, syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	listeningUrl := fmt.Sprintf("%s:%d", cfg.Cfg.Server.Host, cfg.Cfg.Server.Port)
	g, err := graceful.Default(graceful.WithAddr(listeningUrl))
	if err != nil {
		return err
	}
	defer g.Close()

	// gin.SetMode(gin.ReleaseMode)
	g.Use(middlewares.PrometheusMiddleware())
	g.Use(middlewares.CorsMiddleware(cfg.Cfg.Server.Cors))
	g.Use(middlewares.JSONMiddleware())
	g.Use(middlewares.I18nMiddleware())
	// g.Use(middlewares.ProfilingMiddleware(logger.Logger))
	g.Use(middlewares.AccessLogMiddleware(logger.Logger))

	g.GET("/", func(ctx *gin.Context) {
		ctx.JSON(200, map[string]string{"msg": "ok"})
	})
	if err := RegisterV1Handlers(cfg.Cfg, g.Group("/v1/")); err != nil {
		return err
	}

	logger.Logger.Info("started gin", "url", listeningUrl)
	if err := g.RunWithContext(ctx); err != nil && err != context.Canceled {
		return err
	}
	return nil
}
